Support for Magisk 17.4+ Seamless Module

diff --git a/system/bin/energized b/system/bin/energized
--- a/system/bin/energized
+++ b/system/bin/energized
@@ -5,7 +5,7 @@ if [ ! -d /sbin/.core/mirror/bin ]; then
 fi
 # Create Energized Protection Directory if not available 
 if [ ! -d /sdcard/EnergizedProtection ]; then
-    mkdir -p /sdcard/EnergizedProtection;
+    mkdir -p /sdcard/EnergizedProtection || echo "Failed creating Energized directory on sdcard"
 fi
 # Main Screen Starts
 echo "-----------~------------"
@@ -14,16 +14,21 @@ echo "-----------~------------"
 echo "ad.porn.malware blocking."
 echo "Let's make an annoyance free better open internet, altogether!"
 # Check if the Systemless Hosts is enabled or not
-if [ ! -f /sbin/.core/img/.core/hosts ]; then
-    echo "\n\033[33;5;7m[-] Systemless Hosts isn't enabled!\033[0m"
-    echo "\033[37;5;7m[+] Enable it in 'Magisk Manager > Settings > Systemless Hosts'\033[0m"
-    sleep 1
-    echo "\033[36;5;7m[+] Re-run script after enabling Systemless Hosts!\033[0m"
-    echo "\033[31;5;7m[-] Exiting!\033[0m"
-    sleep 3
-    exit 0
+HOST=/sbin/.magisk/img/hosts/system/etc/hosts
+# Check for old non-module-style Seamless Hosts and update path
+if [[ "$(/sbin/magisk -c)" == 17.3* ]]; then
+	HOST=/sbin/.core/img/.core/hosts
+fi
+if [ ! -f "$HOST" ]; then
+	echo "\n\033[33;5;7m[-] Systemless Hosts isn't enabled!\033[0m"
+	echo "\033[37;5;7m[+] Enable it in 'Magisk Manager > Settings > Systemless Hosts'\033[0m"
+	sleep 1
+	echo "\033[36;5;7m[+] Re-run script after enabling Systemless Hosts!\033[0m"
+	echo "\033[31;5;7m[-] Exiting!\033[0m"
+	sleep 3
+	exit 0
 else
-    echo "\033[32;1m\n[+] Systemless Hosts Enabled!\033[0m"
+	echo "\033[32;1m\n[+] Systemless Hosts Enabled!\033[0m"
 fi
 # Check if Other Adblocker is installed Ex. Adaway
 if [ -d /data/data/org.adaway/ ]; then
@@ -50,7 +55,6 @@ fi
 # Aliases, Grep, Wget Variables
 alias wget="/sbin/.core/busybox/wget"
 alias grep="/sbin/.core/busybox/grep"
-HOST=/sbin/.core/img/.core/hosts
 TREADME=/sdcard/EnergizedProtection/readme
 FILTER=/sdcard/EnergizedProtection/filter
 WHITELIST=/sdcard/EnergizedProtection/whitelist
@@ -67,42 +71,42 @@ else
     root="\e[1;32mGRANTED\e[0m";
 fi;
 # Other Variables
-update="\e[1;36m`busybox date -r /sbin/.core/img/.core/hosts`\e[0m"
+update="\e[1;36m`busybox date -r "$HOST"`\e[0m"
 busybox="\e[1;33m`busybox | head -1 | cut -f 2 -d ' '`\e[0m"
-size="\e[1;35m`ls -lah /sbin/.core/img/.core/hosts | awk '{print $5}'`\e[0m"
+size="\e[1;35m`ls -lah "$HOST" | awk '{print $5}'`\e[0m"
 # Check if System's Adblocker is enabled or not
-   [ -f /sbin/.core/img/.core/hosts ];
-if busybox grep -q adblocker /sbin/.core/img/.core/hosts; then
+   [ -f "$HOST" ];
+if busybox grep -q adblocker "$HOST"; then
 	adblocker="\e[1;32mENABLED\e[0m"
 else
 	adblocker="\e[1;31mDISABLED\e[0m"
 fi
 # Check if Energized is applied or not
-	[ -f /sbin/.core/img/.core/hosts ];
-if busybox grep -q adroitadorkhan.github.io /sbin/.core/img/.core/hosts; then
+	[ -f "$HOST" ];
+if busybox grep -q adroitadorkhan.github.io "$HOST"; then
 	eonoff="\e[1;32mENABLED\e[0m"
 else
 	eonoff="\e[1;31mDISABLED\e[0m"
 fi
 # If Energized is enabled, which pack it is
 	[ -f /system/etc/hosts ];
-if busybox grep -q "Energized Ad" /sbin/.core/img/.core/hosts; then
+if busybox grep -q "Energized Ad" "$HOST"; then
 	echeck="\e[1;32mAd Protection\e[0m"	
-elif busybox grep -q "Energized Malware" /sbin/.core/img/.core/hosts; then
+elif busybox grep -q "Energized Malware" "$HOST"; then
 	echeck="\e[1;32mMalware Protection\e[0m"
-elif busybox grep -q "Energized Porn" /sbin/.core/img/.core/hosts; then
+elif busybox grep -q "Energized Porn" "$HOST"; then
 	echeck="\e[1;32mPorn Protection\e[0m"
-elif busybox grep -q "Energized Blu" /sbin/.core/img/.core/hosts; then
+elif busybox grep -q "Energized Blu" "$HOST"; then
 	echeck="\e[1;32mBlu Protection\e[0m"
-elif busybox grep -q "Energized go" /sbin/.core/img/.core/hosts; then
+elif busybox grep -q "Energized go" "$HOST"; then
 	echeck="\e[1;32mBlu go Protection\e[0m"
-elif busybox grep -q "EnergizedLite" /sbin/.core/img/.core/hosts; then
+elif busybox grep -q "EnergizedLite" "$HOST"; then
 	echeck="\e[1;32mLite Protection\e[0m"
-elif busybox grep -q "EnergizedPornLite" /sbin/.core/img/.core/hosts; then
+elif busybox grep -q "EnergizedPornLite" "$HOST"; then
 	echeck="\e[1;32mPorn Lite Protection\e[0m"
-elif busybox grep -q "Energized Ultimate" /sbin/.core/img/.core/hosts; then
+elif busybox grep -q "Energized Ultimate" "$HOST"; then
 	echeck="\e[1;32mUltimate Protection\e[0m"
-elif busybox grep -q "Energized Unified" /sbin/.core/img/.core/hosts; then
+elif busybox grep -q "Energized Unified" "$HOST"; then
 	echeck="\e[1;32mUnified Protection\e[0m"
 else
 	echeck="\e[1;31mNo Pack Detected!\e[0m"
@@ -328,10 +332,10 @@ echo -e -n "\n[+] Energized All-In-One Magisk Module
 		     am start -a android.intent.action.VIEW -d "https://github.com/EnergizedProtection/EnergizedHosts/blob/master/README.md"
 		   fi
 		;;
-		c) rm -rf /sbin/.core/img/.core/hosts
+		c) truncate -s 0 "$HOST"
 		echo "[+] Clearing Hosts File..."
 		sleep 3
-		cat >> /sbin/.core/img/.core/hosts <<EOF
+		cat >> "$HOST" <<EOF
 # Energized - ad.porn.malware blocking.
 # A merged collection of hosts from reputable sources.
 # https://ador.chorompotro.com/energized
